  1) Importar o pacote numpy

In [0]:
import numpy as np

2) Imprimir a versão numpy

In [3]:
print(np.__version__)

1.17.5


3) Criar um vetor 1D de tamanho 10 e uma matriz 2D 2x2 com os 
valores null (0)

In [8]:
z = np.zeros(10)
print(z)
z= np.zeros((2,2))
z

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([[0., 0.],
       [0., 0.]])

4) Criar um vetor 1D de tamanho 10 com os valores null (0) mas o 5º valor deve ser 1

In [11]:
z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

5) Criar um vetor com valores entre 10 e 20

In [25]:
x = np.arange(10,20, 0.5)
x = np.linspace(10,20,5)
x

array([10. , 12.5, 15. , 17.5, 20. ])

6) Inverter um vetor

In [27]:
x = np.arange(20)
print(x)
print(x[::-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


7) Especificar o tipo de dado de um vetor

In [34]:
z=np.zeros(10, dtype=np.int64)
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

8) Criar uma matriz 3x3 com valores de 0 a 8

In [45]:
x= np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

9) Encontrar os índices dos elementos que não são 0 no vetor [1,2,0,0,4,0]

In [47]:
x = [1,2,0,0,4,0]
z = np.nonzero(x)[0].tolist()
z

(array([0, 0, 1, 1, 1, 2, 2, 2]), array([1, 2, 0, 1, 2, 0, 1, 2]))

10) Criar uma matriz identidade 3x3

In [49]:
z = np.eye(3)
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

11) Criar uma matriz 3x3x3 com valores aleatórios

In [53]:
x = np.random.random((3,3,3))
x

array([[[0.20048099, 0.81628205, 0.14279929],
        [0.89528169, 0.87798237, 0.11162297],
        [0.54838773, 0.53321286, 0.24298203]],

       [[0.57265949, 0.83877333, 0.5455918 ],
        [0.10469876, 0.27841654, 0.03848341],
        [0.04681838, 0.06435907, 0.59035759]],

       [[0.63067971, 0.84414852, 0.81445704],
        [0.76580115, 0.79812598, 0.53655365],
        [0.84603701, 0.74571071, 0.21112851]]])

12) Criar uma matriz 5x5 com valores aleatórios em encontrar os valores máximo, mínimo e médio

In [67]:
x = (np.random.random((5,5))*10).astype(int)
print(x)
print('Valor min',x.min())
print('Valor Máx',x.max())
print('Valor Médio',x.mean())

[[2 9 0 9 0]
 [1 2 4 5 7]
 [3 2 1 0 0]
 [4 9 2 4 2]
 [9 1 2 2 2]]
Valor min 0
Valor Máx 9
Valor Médio 3.28


13) Criar uma matriz 5x5 de 1s e preencher as bordas com 0

In [72]:
y=np.ones((5,5))
print(y)
y=np.pad(y, pad_width=1, mode='constant', constant_values=0)
print(y)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


14) Dada a matriz abaixo

In [75]:
a =np.array([[1,2,3],[4,5,6],[7,8,9]])
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

14.1) Imprimir os elementos da segunda coluna

In [76]:
a[:,1]

array([2, 5, 8])

14.2) Imprimir os elementos da 2ª linha

In [77]:
a[1,:]

array([4, 5, 6])

14.3) Mostrar os elementos a partir da 2ª linha e 2ª coluna

In [81]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

15) Multiplicação e adição

In [82]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
a*b

array([ 10,  40,  90, 160])

In [89]:
a = np.array([[0,0,0],[10,10,10],[30,30,30]])
print(a)
b= np.array([[1],[2],[3]])
print(b)
a+b

[[ 0  0  0]
 [10 10 10]
 [30 30 30]]
[[1]
 [2]
 [3]]


array([[ 1,  1,  1],
       [12, 12, 12],
       [33, 33, 33]])

16) Multiplicação de matrizes 5x3 e 3x2 matrix (produto de matrizes)

In [97]:
#np.dot(np.ones((5,3)),np.ones((3,2)))
a= np.array([[1,7],[2,4]])
print(a)
b= np.array([[3,3],[5,2]])
print(b)
#np.dot(a,b)
a@b

[[1 7]
 [2 4]]
[[3 3]
 [5 2]]


array([[38, 17],
       [26, 14]])

17) Dado um vetor 1D, tornar negativos todos os elementos entre 3 e 8 e imprimir os elementos maiores que 5

In [117]:
z = np.arange(11)
z[(z>3)&(z<8)]*=-1
print(z[z>5])

[ 8  9 10]


18) Empilhamento vertical e horizontal

In [121]:
a = np.arange(1,5).reshape(2,2)
print(a)
b = np.arange(5,9).reshape(2,2)
print(b)

c=np.hstack((a,b))
print(c)

d=np.vstack((a,b))
print(d)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


19) Obter valores mínimos, máximos, médios e amplitudes (máximo-mínimo) por eixo

In [129]:
a =np.array([[3,7,5],[8,4,3],[2,4,9]])
print(a)

np.min(a,axis=1) #mínimo por linha
np.min(a,axis=0) #mínimo por coluna

np.max(a,axis=1) #máximo por linha
np.max(a, axis=0) #máximo por coluna

np.mean(a,axis=1) #média por linha
np.mean(a, axis=0) #média por coluna

np.ptp(a, axis=1) #amplitude por linha
np.ptp(a, axis=0) #amplitude por coluna

[[3 7 5]
 [8 4 3]
 [2 4 9]]


array([6, 3, 6])

20) Criar um vetor de tamanho 10 e substituir o valor máximo por 0

In [145]:
x = np.array([0,1,2,3,4,4])

print(x)
np.argmax(x)

x[x==np.max(x)]=9
print(x)

x[np.argmax(x)]=0
print(x)

[0 1 2 3 4 4]
[0 1 2 3 9 9]
[0 1 2 3 0 9]


21) Extrair os valores de uma matriz seguindo a indexação dos elementos

In [148]:
x=np.arange(9).reshape(3,3)
print(x)

for index, value in np.ndenumerate(x):
  print(index, value)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


22) Subtrair a média de cada linha de uma matriz

In [162]:
x = np.arange(9).reshape(3,3)
print(x)
x_med = np.mean(x, axis=1)
print('Média da linha da Matriz',x_med)
x_med_v= x_med.reshape(-1,1)
print(x_med_v)
x=x-x_med_v
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Média da linha da Matriz [1. 4. 7.]
[[1.]
 [4.]
 [7.]]
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [167]:
x = np.arange(9).reshape(3,3)
print(x)
y = x.mean(axis=1, keepdims=True)
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1.]
 [4.]
 [7.]]


23) Trocar linhas de uma matriz

In [183]:
x = np.arange(9).reshape(3,3)
print('Matriz Original:\n',x)
x[:,[1,0]]=x[:,[0,1]] #troca de colunas
print('Troca de colunas:\n',x)
print('\n')
x = np.arange(9).reshape(3,3)
print('Matriz Original:\n',x)
x[[1,0]]=x[[0,1]] #troca de linhas
print('Troca de linhas:\n',x)

Matriz Original:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Troca de colunas:
 [[1 0 2]
 [4 3 5]
 [7 6 8]]


Matriz Original:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Troca de linhas:
 [[3 4 5]
 [0 1 2]
 [6 7 8]]


24) Abrir e salvar dados no formato TXT e NPY

In [193]:
x = np.arange(9).reshape(3,3).astype(int)
print(x)

np.savetxt('saida.txt',x) #salva como float, independente do formato
np.save('saida2.npy',x) #salva no formato definido

b = np.loadtxt('saida.txt')
print(b)
c = np.load('saida2.npy')
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [0]:
from google.colab import files
files.download('saida.txt')